import smoothScroll from "./modules/smooth-scroll.js";
import initScrollAnimation from "./modules/scroll-animation.js";
import initAccordion from "./modules/accordion.js";
import initTabNav from "./modules/tab-nav.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropDownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initNumberAnimation from "./modules/number-animation.js";
import initOperation from "./modules/operation.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";
import initSlide from "./modules/slide.js";

smoothScroll();
initScrollAnimation();
initAccordion();
initTabNav();
initModal();
initTooltip();
initDropDownMenu();
initMenuMobile();
initNumberAnimation();
initOperation();
initFetchBitcoin();
initSlide();
